version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: embeddings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  embedding-service:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/embeddings?sslmode=disable
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - MINIO_BUCKET=documents
      - OPENAI_API_KEY=aa-u7IAZE6Pf8IiCmbt1Xd2PY5VFOadi7kMtREvYBefB9hrwytT
      - OPENAI_MODEL=text-embedding-3-small
      - LOG_LEVEL=info
    ports:
      - "8080:8080"
    depends_on:
      - minio
    restart: always

volumes:
  postgres_data:
  minio_data:
